### ISSUE TITLE
$base-font-size sets % on body and creates a floating-point $base-em-font-size (with Typesetted)

### ISSUE THREAD

**Issue by ianrose** [ianrose/typesettings#16]
Example

``` scss
$base-font-size: 13px;
```

Compiles:

``` scss
$base-em-font-size: 0.8125em;
html {
 font-size: 81.25%;
}
```

[edited] cc. @paolodina 

Too much compounding :frowning:
